version: '3.7'
services:
  notebook:
    image: jupyter/datascience-notebook
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=yes

  db:
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: my_pASSword
    restart: always
